MK8_VEHICLES = [
    "Standard Kart",
    "Pipe Frame",
    "Mach 8",
    "Steel Driver",
    "Cat Cruiser",
    "Circuit Special",
    "Tri-Speeder",
    "Badwagon",
    "Prancer",
    "Biddybuggy",
    "Buggybud",
    "Landship",
    "Sneeker",
    "Bounder",
    "Sports Coupe",
    "Gold Standard",
    "Gold Kart",
    "GLA",
    "W 25 Silver Arrow",
    "300 SL Roadster",
    "Blue Falcon",
    "Tanooki Kart",
    "B Dasher",
    "Streetle",
    "P-Wing",
    "Koopa Clown",
    "Standard Bike",
    "The Duke",
    "Flame Rider",
    "Varmint",
    "Mr. Scooty",
    "Master Cycle Zero",
    "City Tripper",
    "Comet",
    "Sport Bike",
    "Jet Bike",
    "Yoshi Bike",
    "Master Cycle",
    "Standard ATV",
    "Standard Quad",
    "Wild Wiggler",
    "Teddy Buggy",
    "Bone Rattler",
    "Splat Buggy",
    "Inkstriker"
]
